{{- if .Values.gitRepository.credentials.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: repo-{{ .Values.environment }}-creds
  namespace: {{ .Release.Namespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
    {{- include "argocd.labels" . | nindent 4 }}
type: Opaque
stringData:
  type: git
  url: {{ .Values.gitRepository.url }}
  username: {{ .Values.gitRepository.credentials.username }}
  password: {{ .Values.gitRepository.credentials.password }}
{{- end }}
