apiVersion: v2
name: jenkins
description: A Helm chart for Jenkins CI/CD server
type: application
version: 0.1.0
appVersion: "2.426.1"

dependencies:
  - name: jenkins
    version: 5.8.27
    repository: https://charts.jenkins.io
