apiVersion: v2
name: argocd
description: A Helm chart for Argo CD GitOps deployment
type: application
version: 0.1.0
appVersion: "2.11.0"

dependencies:
  - name: argo-cd
    version: 5.51.6
    repository: https://argoproj.github.io/argo-helm
